mi/urls.py
from django.urls import path
from mi.views import *
app_name='mi'
urlpatterns=[
    path('rohit/',rohit,name='rohit'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import mi
from csk.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dhoni/',dhoni,name='dhoni'),
    path('mi/',include('mi.urls')),
]

csk/models.py
from django.db import models

# Create your models here.

mi/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')

mi/views.py
from django.shortcuts import render

# Create your views here.
def rohit(request):
    return render(request,'rohit.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Dhoni page</h1>
        <h1>we are using generic url mapping to get this page</h1>
        <a href="{% url 'mi:rohit' %}"> Go to rohit page</a>
    </center>
    
</body>
</html>

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to rohit page</h1>
        <h1>This is rendered by specific url mapping</h1>
        <a href="{% url 'dhoni'%}">Navigate to dhoni</a>
    </center>
</body>
</html>